module robotics_benchmark_msgs {
  module msg {
    struct BigSensor {
      uint64 timestamp_ns;
      uint32 sequence_number;
      uint32 width;
      uint32 height;
      uint32 row_stride;
      string encoding;
      sequence<octet> data;
    };
  };
};
