import ctypes


class WideFlat(ctypes.Structure):
    _fields_ = [
        ("timestamp_ns", ctypes.c_uint64),
        ("sequence", ctypes.c_uint32),
        ("channel_00", ctypes.c_double),
        ("channel_01", ctypes.c_double),
        ("channel_02", ctypes.c_double),
        ("channel_03", ctypes.c_double),
        ("channel_04", ctypes.c_double),
        ("channel_05", ctypes.c_double),
        ("channel_06", ctypes.c_double),
        ("channel_07", ctypes.c_double),
        ("channel_08", ctypes.c_double),
        ("channel_09", ctypes.c_double),
        ("channel_10", ctypes.c_double),
        ("channel_11", ctypes.c_double),
        ("channel_12", ctypes.c_double),
        ("channel_13", ctypes.c_double),
        ("channel_14", ctypes.c_double),
        ("channel_15", ctypes.c_double),
        ("channel_16", ctypes.c_double),
        ("channel_17", ctypes.c_double),
        ("channel_18", ctypes.c_double),
        ("channel_19", ctypes.c_double),
        ("channel_20", ctypes.c_double),
        ("channel_21", ctypes.c_double),
        ("channel_22", ctypes.c_double),
        ("channel_23", ctypes.c_double),
        ("channel_24", ctypes.c_double),
        ("channel_25", ctypes.c_double),
        ("channel_26", ctypes.c_double),
        ("channel_27", ctypes.c_double),
        ("channel_28", ctypes.c_double),
        ("channel_29", ctypes.c_double),
        ("channel_30", ctypes.c_double),
        ("channel_31", ctypes.c_double),
    ]
